---
- name: Creating Two EC2 Instances Behind Elastic Application Load Balance
  hosts: localhost
  vars_files: vars.yml
  connection: local
  become: true
  module_defaults:
    ansible.builtin.setup:
      gather_subset:
        - '!min'
        - '!all'
  roles:
    - role
