- name: Test
  hosts: all
  connection: local
  vars_files: secrets.yml
  become: true
  tasks:
  - name: Create Instances
    amazon.aws.ec2_instance:
      name: Server-LB
      state: present
      image_id: ami-0574da719dca65348
      count: 1
      instance_type: t2.micro
 #   security_group: "{{ sg.group_name }}"
 #   vpc_subnet_id: "{{ privatesubnet.subnet.id }}"
      user_data: "{{ lookup('file', 'user_data.sh') }}"
      key_name: windows11
      region: us-east-1
      access_key: "{{ aws_access_key }}"
      secret_key: "{{ aws_secret_key }}"
      network:
        assign_public_ip: true
    register: instance_data
