---
- name: Creating AutoScaling Group
  amazon.aws.autoscaling_group:
    name: BiServerASG
    region: "{{ region }}"
    target_group_arns: "{{ tg.target_group_arn }}"
    availability_zones: [ "{{ az[0] }}", "{{ az[1] }}" ]
    launch_config_name: 'BiServer-LC'
    min_size: 0
    max_size: 2
    vpc_zone_identifier: [ "{{ privatesubnet.subnet.id }}", "{{ privatesubnet1.subnet.id }}" ]
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: asg
