---
- name: Destroy Instances
  amazon.aws.ec2_instance:
    instance_ids:
      - "{{ server_lb_1_id }}"
      - "{{ server_lb_2_id }}"
      - "{{ nat_id }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy

- name: Destroy Load Balancer
  amazon.aws.elb_application_lb:
    name: "{{ lb_name }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy

- name: Destroy Target Group
  community.aws.elb_target_group:
    name: "{{ tg_name }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy

- name: Destroy Autoscaling Group
  amazon.aws.autoscaling_group:
    name: "{{ asg_name }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy

- name: Destroy Launch Configuration
  community.aws.autoscaling_launch_config:
    name: "{{ lc_name }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy

- name: Destroy Subnets
  amazon.aws.ec2_vpc_subnet:
    cidr: "{{ item }}"
    vpc_id: "{{ vpc.id }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  loop: "{{ subnets_cidr }}"
  tags: destroy

- name: Destroy Route Tables
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ vpc.id }}"
    lookup: id
    route_table_id: "{{  item }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  loop: "{{ rt_ids }}"
  tags: destroy

- name: Destroy Internet Gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.id }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy

- name: Destroy Security Groups
  amazon.aws.ec2_security_group:
    group_id: "{{ item }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  loop: "{{ sg_ids }}"
  tags: destroy

- name: Destroy VPC and its remaining components
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc.name }}"
    vpc_id: "{{ vpc.id }}"
    state: absent
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  tags: destroy
