---
- name: Create Internet Gateway for VPC
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: igw

- name: Lookup Main Route Table
  amazon.aws.ec2_vpc_route_table_info:
    filters:
      vpc-id: "{{ vpc.vpc.id }}"
      association.main: true
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: route_table
