---
- name: Create Instances
  amazon.aws.ec2_instance:
    name: 'Server-LB-{{ item.index }}'
    state: present
    image_id: ami-00aa9d3df94c6c354
    instance_type: t2.micro
    security_group: "{{ sg.group_name }}"
    vpc_subnet_id:  "{{ item.id }}"
    user_data: "{{ lookup('file', 'user_data.sh') }}"
    key_name: windows11
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    network:
      assign_public_ip: false
  register: instance_data
  with_items:
    - { id: "{{ privatesubnet.subnet.id }}", index: 1 }
    - { id: "{{ privatesubnet1.subnet.id }}", index: 2 }

- pause:
    seconds: 60
    prompt: "Waiting for the instances to go into running state"
