---
- name: Create Launch Configuration for AutoScaling
  community.aws.autoscaling_launch_config:
    name: BiServer-LC
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_id: "{{ item }}"
    security_groups: "{{ sg.group_name }}"
    user_data: "{{ lookup('file', 'user_data.sh') }}"
  with_items:
    - "{{ instance_data.results[0].instance_ids[0] }}"
    - "{{ instance_data.results[1].instance_ids[0] }}"
  register: lc
