---
- name: Create Load Balancer
  amazon.aws.elb_application_lb:
    name: BiServer-LB
    region: "{{ region }}"
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: forward
            TargetGroupName: BiServer
    state: present
    security_groups:
      - "{{ sg2.group_name }}"
    subnets:
      - "{{ publicsubnet.subnet.id }}"
      - "{{ publicsubnet1.subnet.id }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: load_balancer
