---
# tasks file for role
- name: Create VPC
  import_tasks: VPC.yml
- name: Create Internet Gateway
  import_tasks: IGW.yml
- name: Create Subnets
  import_tasks: Subnets.yml
- name: Create and Associate Route Table to Public Subnet
  import_tasks: RouteTable.yml
- name: Create Security Groups
  import_tasks: SG.yml
- name: Create NAT Instance.yml
  import_tasks: NATInstance.yml
- name: Create Instances
  import_tasks: Instances.yml
- name: Create Target Group
  import_tasks: TG.yml
- name: Create Load Balancer
  import_tasks: LoadBalancer.yml
