---
- name: Create Private Subnet in AZ a
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.1.0/24
    region: us-east-1
    az: us-east-1a
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    tags:
      Name: BiServer Private
  register: privatesubnet

- name: Create Private Subnet in AZ b
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.2.0/24
    region: us-east-1
    az: us-east-1b
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    tags:
      Name: BiServer Private1
  register: privatesubnet1

- name: Create Public Subnet in AZ a
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.3.0/24
    region: us-east-1
    az: us-east-1a
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    tags:
      Name: BiServer Public
  register: publicsubnet

- name: Create Public Subnet in AZ b
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.0.4.0/24
    region: us-east-1
    az: us-east-1b
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
    tags:
      Name: BiServer Public 1
  register: publicsubnet1
