---
- name: Create Target Group
  community.aws.elb_target_group:
    name: BiServer
    protocol: http
    port: 80
    health_check_port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    targets:
      - Id: "{{ instance_data.results[0].instance_ids[0] }}"
        Port: 80
      - Id: "{{ instance_data.results[1].instance_ids[0] }}"
        Port: 80
    state: present
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: tg
