---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: BiServer-VPC
    cidr_block: 10.0.0.0/16
    region: us-east-1
    access_key: "{{ aws_access_key }}"
    secret_key: "{{ aws_secret_key }}"
  register: vpc
