---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: BiServer-VPC
    cidr_block: 10.0.0.0/16
    region: "{{ region }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  register: vpc
